// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoMuralis.Data;

#nullable disable

namespace ProjetoMuralis.Migrations
{
    [DbContext(typeof(BancoContexto))]
    [Migration("20221107133831_CriandoTabelaFuc")]
    partial class CriandoTabelaFuc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjetoMuralis.Models.FuncionariosModel", b =>
                {
                    b.Property<int>("Id_func")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_func"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao_func")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro_func")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email_func")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login_fuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_func")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil_func")
                        .HasColumnType("int");

                    b.Property<string>("Senha_func")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_func");

                    b.ToTable("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
